// Copyright 2017-2022 @subwallet/wagmi-connector authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/wagmi-connector', path: 'auto', type: 'auto', version: '0.2.1' };
