// Copyright 2017-2022 @subwallet/wallet-connect authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/wallet-connect', path: 'auto', type: 'auto', version: '0.2.3' };
