// Copyright 2017-2022 @subwallet/web3-react-subwallet-connector-v6 authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Empty template, auto-generated by @polkadot/dev

export default [];
