// Copyright 2017-2022 @subwallet/web3-react-subwallet-connector-v6 authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/web3-react-subwallet-connector-v6', path: 'auto', type: 'auto', version: '0.2.3' };
